# To print a marksheet in Python.
r=int(input("Rollno-"))
n=str(input("Name-"))
c=str(input("Course Name-"))
e=int(input("Marks in english-"))
m=int(input("Marks in maths-"))
s=int(input("Marks in science-"))
h=int(input("Marks in history-"))
g=int(input("Marks in geography-"))
l=int(input("Marks in lab-"))
print('*'*30, "Marksheet",'*'*30)
print("Roll.No-", r)
print("Name-", n)
print("Course Name-", c)
print('*'*71)
print("subject",'               ', "Total",'               ', "Marks")
print('*'*71)
print("English",'               ', "100",'                  ', e)
print("Maths",'                 ', "100",'                  ', m)
print("Science",'               ', "100",'                  ', s)
print("History",'               ', "100",'                  ', h)
print("Geography",'             ', "100",'                  ', g)
print("Lab",'                   ', "100",'                  ', l)
print('*'*71)
print("Total",'                 ', "700",'                  ', "480")
p=(480/700)*100
print("Percentage",'            ',p,'%')
print('*'*31, "Thankyou",'*'*31)
